[metadata]
name = shfmt_py
version = 3.14.1-1
description = Shell source code formatter
url = https://github.com/scop/pre-commit-shfmt
# shfmt proper and Python packaging related files
license = BSD 3-Clause AND Apache Software License AND MIT License
classifiers =
    Intended Audience :: Developers
    Operating System :: MacOS
    Operating System :: Microsoft :: Windows
    Operating System :: POSIX :: Linux
    Programming Language :: Go
project_urls =
    Upstream = https://github.com/mvdan/sh#shfmt

[options]
packages =
python_requires = >=3.8
setup_requires =
    setuptools-download

[setuptools_download]
download_scripts =
    [shfmt]
    group = shfmt-binary
    marker = sys_platform == "darwin" and platform_machine == "x86_64"
    url = https://github.com/mvdan/sh/releases/download/v3.14.1/shfmt_v3.14.1_darwin_amd64
    sha256 = d33eee0da0f92835b3562e9767a05cee7e4eaeef47daa03bfd09da17b4b590a6
    [shfmt]
    group = shfmt-binary
    marker = sys_platform == "darwin" and platform_machine == "arm64"
    url = https://github.com/mvdan/sh/releases/download/v3.14.1/shfmt_v3.14.1_darwin_arm64
    sha256 = b7c872db63553ccffc7253aba3ed7d4885a27d83f1ba567b1138c6315a5847e5
    [shfmt]
    group = shfmt-binary
    # TODO: verify i386
    marker = sys_platform == "linux" and platform_machine == "i386"
    marker = sys_platform == "linux" and platform_machine == "i686"
    url = https://github.com/mvdan/sh/releases/download/v3.14.1/shfmt_v3.14.1_linux_386
    sha256 = aad6f0bd6285910c152091ba58b5509aa88eb8a2a81a2d72cf2048a8a78c27f4
    [shfmt]
    group = shfmt-binary
    marker = sys_platform == "linux" and platform_machine == "x86_64"
    url = https://github.com/mvdan/sh/releases/download/v3.14.1/shfmt_v3.14.1_linux_amd64
    sha256 = 76e77641faa025814b77f153b29796b8e6fa2fca03e0c76a691608b86c7ea7bf
    [shfmt]
    group = shfmt-binary
    # TODO: verify armv6hf
    marker = sys_platform == "linux" and platform_machine == "armv6hf"
    marker = sys_platform == "linux" and platform_machine == "armv7l"
    url = https://github.com/mvdan/sh/releases/download/v3.14.1/shfmt_v3.14.1_linux_arm
    sha256 = ede6c4adefeda196d963906daa7c1f20094e6def7a98bcb9f4c74079babf1eca
    [shfmt]
    group = shfmt-binary
    marker = sys_platform == "linux" and platform_machine == "aarch64"
    url = https://github.com/mvdan/sh/releases/download/v3.14.1/shfmt_v3.14.1_linux_arm64
    sha256 = 5f2db09dae91fca848f7adbdd014632e921a383863a2ad7e0450ad3aba0c6489
    [shfmt.exe]
    group = shfmt-binary
    # TODO: verify both
    marker = sys_platform == "win32" and platform_machine == "x86"
    marker = sys_platform == "cygwin" and platform_machine == "i386"
    url = https://github.com/mvdan/sh/releases/download/v3.14.1/shfmt_v3.14.1_windows_386.exe
    sha256 = b6f171113e7359f44d5ffdc93a90b93a7d405aa8847129a6982e10fe4d356f1e
    [shfmt.exe]
    group = shfmt-binary
    marker = sys_platform == "win32" and platform_machine == "AMD64"
    marker = sys_platform == "cygwin" and platform_machine == "x86_64"
    url = https://github.com/mvdan/sh/releases/download/v3.14.1/shfmt_v3.14.1_windows_amd64.exe
    sha256 = 13629ce28442ca80b6b5a819f7574ab39e1c28c6e26734ca816c9714e04851df
