name: Tag checks

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run checks
        run: |
          grep -P --color=always "\s+(?<=rev: )$GITHUB_REF_NAME$" README.md
          ver=${GITHUB_REF_NAME%-*}
          grep -P --color=always "(?<=/shfmt@)$ver(?=])" .pre-commit-hooks.yaml
          grep -P --color=always "(?<=/shfmt:)$ver(?=@)" .pre-commit-hooks.yaml
