name: Main push and PR checks

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # No caching as we're expected to run rarely
      - uses: j178/prek-action@53276d8b0d10f8b6672aa85b4588c6921d0370cc # v2.0.1
        with:
          cache: false
          install-only: true
      - name: Run checks
        shell: bash
        run: |
          set -euxo pipefail
          shfmt_docker=$(type docker &>/dev/null && echo shfmt-docker || :)
          for hook in shfmt shfmt-src $shfmt_docker; do
            prek try-repo . $hook --files .github/workflows/test-good.sh
          done
          for hook in shfmt $shfmt_docker; do
            ! prek try-repo . $hook --files .github/workflows/test-bad.sh
            ! git diff --exit-code .github/workflows/test-bad.sh
            git restore .github/workflows/test-bad.sh
          done
